version: '3.5'

services:
  db:
    image: postgres:14.1
    volumes:
      - database_volume:/var/lib/postgresql/data
    networks:
      - database_network
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  redis:
    image: redis:6.2.6
    networks:
      - redis_network

  django:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DJANGO_SECRET_KEY
    depends_on:
      - db
      - redis
    command: gunicorn appname.wsgi -c gunicorn.cfg.py
    volumes:
      - ./_app:/usr/src/app
      # Enable this volume if you want to use Caddy/Nginx/etc... for handling HTTP traffic
      - static_files_volume:/usr/src/app/static
    networks:
      - database_network
      - redis_network
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=0
      - DJANGO_SECRET_KEY
      - POSTGRES_USER
      - POSTGRES_PASSWORD

volumes:
  static_files_volume:
  database_volume:

networks:
  database_network:
  redis_network:
